### ISSUE TITLE
Coefficient isn't specified in apply_gravity when useStrongGravity is True

### ISSUE THREAD

**Issue by clyang** [bhargavchippada/forceatlas2#12]
When `apply_gravity` function is called with `useStrongGravity=True`. The `strongGravity` function will be called without assigning `coefficient` value.
https://github.com/bhargavchippada/forceatlas2/blob/ab0daf9838bbe2022a9a392d9f6a2c335c766550/fa2/fa2util.py#L125-L131

Meanwhile, the default value of  `coefficient ` in `strongGravity` function is `0`.
https://github.com/bhargavchippada/forceatlas2/blob/ab0daf9838bbe2022a9a392d9f6a2c335c766550/fa2/fa2util.py#L84-L91

It forces all factor to be `0` and makes no different to node's position.

**Comment by bhargavchippada** [comment]
@clyang Thanks a bunch, I will fix the bug. I am supposed to pass scalingRatio as the coefficient for strongGravity method. Source: [Java code](https://github.com/gephi/gephi/blob/master/modules/LayoutPlugin/src/main/java/org/gephi/layout/plugin/forceAtlas2/ForceAtlas2.java).

**Comment by bhargavchippada** [comment]
@clyang I fixed this bug but I will publish the new version on pip later this summer along with some other enhancements. You can check the latest commit/s.
