### ISSUE TITLE
Different results compared to Gephi

### ISSUE THREAD

**Issue by eybee** [bhargavchippada/forceatlas2#13]
My goal is to visualize NetworkX graphs with Gephi's ForceAtlas 2 algorithm without having to use Gephi.
I tested this library by importing the same graph once in Gephi and once in NetworkX. 
I used the same algorithm parameters for both but got totally different layout results. This is the layout using the python version of ForceAtlas:
![image](https://user-images.githubusercontent.com/13030349/60668784-0e4c0e00-9e6d-11e9-890c-e4d9caa0bc15.png)

And this is what I get when running Gephi:
![image](https://user-images.githubusercontent.com/13030349/60668924-61be5c00-9e6d-11e9-8f2f-753428889b36.png)

The main issue is that the edges in the plot of the python result are not separated from each other as it is the case when using Gephi.

**Comment by bhargavchippada** [comment]
@eybee Sorry for the late reply, can you share the example you are running along with data to replicate? It could be due to a lot of factors.
