### ISSUE TITLE
Very slow on a large graph needs threading

### ISSUE THREAD

**Issue by JoeyC1990** [bhargavchippada/forceatlas2#20]
Hi,

I am trying to use this to generate a force directed graph outside of gephi.

The size of the graph is significant at 200K+ nodes.

I have tried to fork but cython is a step further than my skills.

If you can advise I can perhaps help.

Cheers

Joe

**Comment by bhargavchippada** [comment]
@JoeyC1990 I did try doing this earlier and I am gonna give another try this summer for the next version. Look out for it :)
