### ISSUE TITLE
Potential Multithreaded merge

### ISSUE THREAD

**Issue by herbertfreeze** [bhargavchippada/forceatlas2#21]
Hi,

There's been a recent release of multithreaded implementation in Java: 
https://github.com/klarman-cell-observatory/forceatlas2

Are there any plans to integrate this? It'd be very much appreciated!

Best,
Herbert

**Comment by bhargavchippada** [comment]
@herbertfreeze Hi Herbert, I will try to integrate this over summer :)

**Comment by YubinXie** [comment]
current single core is very slow for me when there are 100k points. It would be great to have multithreading. Thanks!

**Comment by herbertfreeze** [comment]
Hey Bhargav, hope you're doing well, just wanted to check in to see if there's been any updates :)

**Comment by YubinXie** [comment]
Hi Bhargav, sorry for repeating but just wanted to check if there is still a plan for multithread. Thanks!!
