### ISSUE TITLE
weighted or not?

### ISSUE THREAD

**Issue by tarikaltuncu** [bhargavchippada/forceatlas2#4]
Hi,

Sample code defines edgeWeightInfluence = 1.0 but in the header comments of master/fa2/forceatlas2.py says weighted version is not implemented. 

So it's confusing. Would this forceatlas2 act right on our weighted graphs or not?

**Comment by bhargavchippada** [comment]
Sorry for the late reply. Yes, forceatlas2 can act on weighted graphs. I fixed the typo in this lastest [commit](https://github.com/bhargavchippada/forceatlas2/commit/a3747cf5f0f84448da315bbd3bb1c6bd9e7d4c5f). Thanks for noticing!
