### ISSUE TITLE
iterative reporting

### ISSUE THREAD

**Issue by jim-bo** [bhargavchippada/forceatlas2#5]
Is there anyway to extract updates of the layout at regular intervals while the algorithm is running on large graphs?

**Comment by bhargavchippada** [comment]
Maybe you do something like this,
```python
import networkx as nx
from fa2 import ForceAtlas2
import matplotlib.pyplot as plt

G = nx.karate_club_graph()

forceatlas2 = ForceAtlas2(...., verbose=False)
# getting positions after 10 iterations
positions1 = forceatlas2.forceatlas2_networkx_layout(G, pos=None, iterations=10)

# getting positions after 10 more iterations (20 iterations in total), pass pos = positions1
positions2 = forceatlas2.forceatlas2_networkx_layout(G, pos=positions1, iterations=10)
```
Like this, you can run forceatlas2 algo in a for-loop passing the previous time's positions to extract updates of the layout at regular intervals. Hope this helps. Let me know if it's not clear. Cheers!
