### ISSUE TITLE
initialization is ignored after one iteration

### ISSUE THREAD

**Issue by falexwolf** [bhargavchippada/forceatlas2#8]
Hi! This a very nice package!

This should be very easy to reproduce for you, if not I'll assemble a small-scale example: after one iteration, no trace of the init pos is visible in the layout, it looks almost random. After 0 iterations, one perfectly recovers the provided initial positions. Is this behavior intended!

  Alex

**Comment by bhargavchippada** [comment]
Thanks, Alex. Maybe the initial positions you provided are far from equilibrium so the forces in the graph were strong enough to move them a lot in just one iteration?
The algorithm tries to reach equilibrium as fast as possible so there are no guarantees the final state (or state after 1 iteration) will look similar to initial positions provided.
I believe you can decrease **jitterTolerance** for lower speed and more precision, that way maybe you can find traces of inititial positions after 1 iteration... See if this and tweaking other parameters helps :)

**Comment by falexwolf** [comment]
Thank you! The initial positions should be pretty close to what is optimum... They are from UMAP and other topology-aware methods...

Thanks for the `jitterTolerance` hint. I'll play around a bit more and hopefully have time to prepare something reproducible for you...

Interestingly, the final layout still seems to remember my initial positions after, say 100 iterations. Then, the global topology absolutely matches what I provided as initial positions... That's kind of a really weird effect.

PS: I'm looking at a very hard large-scale case where it's impossible to compute something meaningful with random initialization...
